server:
  port: 8002

  
spring:
  application:
    name: product-service 
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: Vishnu@139




eureka:
  client:
    fetch-registry: true
    register-with-eureka: true 