server:
  port: 8005
  
  
spring:
  application:
     name: appointment-service
  datasource:
     url: jdbc:mysql://localhost:3306/brilliomicroservice
     name: root
     password: Vishnu@139
     
eureka:
   client:
     fetch-registry: true
     register-with-eureka: true
     serviceUrl:
       defaultZone: http://localhost:8761/eureka/
   instance:
    hostname: localhost
