server:
  port: 8003
  
  
spring:
  application:
    name: patient-service
  datasource:
    url: jdbc:mysql://localhost:3306/brilliomicroservice
    username: root
    password: Vishnu@139
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true 
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost